pipeline:
    Linux Build:
        image: golang:1.12.6-alpine
        pull: true
        commands:
            - apk add git
            - go get github.com/logrusorgru/aurora
            - go get github.com/tidwall/gjson
            - go get github.com/satori/go.uuid
            - go get github.com/pierrec/lz4
            - cd $GOPATH/src/github.com/pierrec/lz4 && git fetch && git checkout v3.0.1
            - go get github.com/mholt/archiver
            - CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o McBoop .
            - sha256sum McBoop | head -c 64 > McBoop.sha256
    Windows Build:
      image: golang:1.12.6-alpine
      pull: true
      commands:
        - apk add git
        - go get github.com/logrusorgru/aurora
        - go get github.com/tidwall/gjson
        - go get github.com/satori/go.uuid
        - go get github.com/pierrec/lz4
        - cd $GOPATH/src/github.com/pierrec/lz4 && git fetch && git checkout v3.0.1
        - go get github.com/mholt/archiver
        - CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o McBoop.exe .
        - sha256sum McBoop.exe | head -c 64 > McBoop.exe.sha256
    Deploy:
        image: plugins/s3
        bucket: boops-deploy
        acl: public-read
        region: us-east-1
        source: McBoop*
        target: /McBoop
        secrets: [ aws_access_key_id, aws_secret_access_key ]
