pipeline:
  jdk11build:
    image: openjdk:11-jdk
    commands:
      - ./gradlew build
  jdk8build:
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
      - mv build/libs/Mcboop.jar .
  deploy:
    image: plugins/s3
    bucket: boops-deploy
    acl: public-read
    region: us-east-1
    source: McBoop.jar
    target: McBoop
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
