pipeline:
  jdk11build:
    image: openjdk:11-jdk
    commands:
      - ./gradlew build
  jdk8build:
    image: openjdk:8-jdk
    commands:
      - ./gradlew build
      - mv build/libs/McBoop.jar .
      - sha1sum McBoop.jar | head -c 40 > McBoop.jar.sha1
  deploy:
    image: plugins/s3
    bucket: boops-deploy
    acl: public-read
    region: us-east-1
    source: McBoop.*
    target: /McBoop
    secrets: [ aws_access_key_id, aws_secret_access_key ]
