version: 2.1
jobs:
  build:
    docker:
      - image: golang:1.14.5-alpine
    steps:
      - checkout
      - run: apk add git py3-pip
      - run: pip install awscli
      - run: CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -a -ldflags '-extldflags "-static"' -o McBoop .
      - run: CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o McBoop.exe .
      - run: sed -i "s/aaaaa/$(sha256sum McBoop | head -c 64)/" McBoop.json
      - run: sed -i "s/bbbbb/$(sha256sum McBoop.exe | head -c 64)/" McBoop.json
      - run: aws s3 cp McBoop s3://boops-deploy/McBoop/McBoop --acl public-read
      - run: aws s3 cp McBoop.exe s3://boops-deploy/McBoop/McBoop.exe --acl public-read
      - run: aws s3 cp McBoop.json s3://boops-deploy/McBoop/McBoop.json --acl public-read
      - run: sed -i "s/commit/$(git rev-parse HEAD)/" .circleci/inv-batch.json
      - run: aws cloudfront create-invalidation --distribution-id EYO1QOMN5FQJH --invalidation-batch file://.circleci/inv-batch.json
